### ISSUE TITLE
Makefile:567: recipe for target 'libasn1cskeletons_la-ANY.lo' failed

### ISSUE THREAD

**Issue by zosrothko** [d-chugunov/asn1cpp#1]
Hi

On Fedora 23, one gets the error below running make check

make[2]: Entering directory '/home/fandre/isode/asn1cpp/skeletons'
make  libasn1cskeletons.la
make[3]: Entering directory '/home/fandre/isode/asn1cpp/skeletons'
source='ANY.cpp' object='libasn1cskeletons_la-ANY.lo' libtool=yes \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..     -std=c++11  -c -o libasn1cskeletons_la-ANY.lo `test -f 'ANY.cpp' || echo './'`ANY.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -std=c++11 -c ANY.cpp  -o .libs/libasn1cskeletons_la-ANY.o
Makefile:567: recipe for target 'libasn1cskeletons_la-ANY.lo' failed
make[3]: Leaving directory '/home/fandre/isode/asn1cpp/skeletons'
Makefile:1100: recipe for target 'check-am' failed
make[2]: Leaving directory '/home/fandre/isode/asn1cpp/skeletons'
Makefile:916: recipe for target 'check-recursive' failed
make[1]: Leaving directory '/home/fandre/isode/asn1cpp/skeletons'
Makefile:394: recipe for target 'check-recursive' failed

[fandre@fedora-x86-idefix asn1cpp]$ uname -a
Linux fedora-idefix 4.4.5-300.fc23.x86_64 #1 SMP Thu Mar 10 17:54:44 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

[fandre@fedora-x86-idefix asn1cpp]$ gcc --version
gcc (GCC) 5.3.1 20151207 (Red Hat 5.3.1-2)
Copyright © 2015 Free Software Foundation, Inc.
Ce logiciel est libre; voir les sources pour les conditions de copie.  Il n'y a PAS
GARANTIE; ni implicite pour le MARCHANDAGE ou pour un BUT PARTICULIER.

**Comment by d-chugunov** [comment]
I have downloaded and installed Fedora 23 Workstation from the official website. It is shipped with gcc 5.1.1. So here is my configuration:
[user@localhost asn1cpp]$ uname -a
Linux localhost.localdomain 4.2.3-300.fc23.x86_64 #1 SMP Mon Oct 5 15:42:54 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[user@localhost asn1cpp]$ gcc --version
gcc (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)
Copyright (C) 2015 Free Software Foundation, Inc.
Это свободно распространяемое программное обеспечение. Условия копирования
приведены в исходных текстах. Без гарантии каких-либо качеств, включая 
коммерческую ценность и применимость для каких-либо целей.

And `make check` finished without any error. What should I do to obtain your configuration?

**Comment by zosrothko** [comment]
I have no idea.. except that I am running the server and not the workstation but I doubt it makes a difference...

**Comment by zosrothko** [comment]
It seems that libtool does not find the g++ compiler
make[2]: Entering directory '/home/fandre/isode/asn1cpp/skeletons'
source='ANY.cpp' object='libasn1cskeletons_la-ANY.lo' libtool=yes \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..     -std=c++11  -c -o libasn1cskeletons_la-ANY.lo `test -f 'ANY.cpp' || echo './'`ANY.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -std=c++11 -c ANY.cpp  -o .libs/libasn1cskeletons_la-ANY.o
../libtool: line 1125: g++: command not found

The g++ compiler front end is missing in the distribution

**Comment by zosrothko** [comment]
Installing gcc-c++ fixes the issue but maybe the configure script should check that g++ is avaialbe.

**Comment by d-chugunov** [comment]
Actually configure script does this check using `AC_PROG_CXX` macro in configure.ac, but I don't know how to force it interrupting configuring in the case the compiler is missing. Any ideas?

**Comment by zosrothko** [comment]
Not really... but adding a test to compile a c++ program will fail...Could this interrupt the configuration process?

**Comment by d-chugunov** [comment]
What can I add to configure.ac?
